openapi: 3.0.1
info:
  title: Gmail Draft Plugin API
  version: '1.0.0'
servers:
  - url: https://gym-spotter-ai-portal-plugin-gmail.onrender.com
paths:
  /gmail/draft:
    post:
      summary: Create a draft email
      operationId: createDraft
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        '200':
          description: Draft created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
        '401':
          description: Unauthorized
        '500':
          description: Server Error
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    EmailRequest:
      type: object
      properties:
        to:
          type: string
          description: Recipient email address
        subject:
          type: string
          description: Email subject
        body:
          type: string
          description: Email body content
      required:
        - to
        - subject
        - body
    EmailResponse:
      type: object
      properties:
        id:
          type: string
          description: Draft ID
