openapi: 3.0.1
info:
  title: Gmail Draft Plugin API
  version: '1.0.0'
servers:
  - url: https://gym-spotter-ai-portal-plugin-gmail.onrender.com
paths:
  /gmail/draft:
    post:
      summary: Create a draft email
      operationId: createDraft
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        '200':
          description: Draft created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Server Error
      security:
        - oauth2: [ "https://www.googleapis.com/auth/gmail.compose" ]
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/gmail.compose: "Create and modify drafts"
  schemas:
    EmailRequest:
      type: object
      properties:
        to:
          type: string
          description: Recipient email address
        subject:
          type: string
          description: Email subject
        body:
          type: string
          description: Email body content in HTML format
      required:
        - to
        - subject
        - body
    EmailResponse:
      type: object
      properties:
        id:
          type: string
          description: Draft ID
